#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SKILL_DIR/../../.." && pwd)"
REFERENCES_DIR="$SKILL_DIR/references"

mkdir -p "$REFERENCES_DIR"

TMP_RULES="$(mktemp)"
TMP_TOPICS="$(mktemp)"
trap 'rm -f "$TMP_RULES" "$TMP_TOPICS"' EXIT

(
  cd "$REPO_ROOT"
  rg --files generative -g '*.rules.md' -g '*.rules.xml' -g '**/rules/*.md' | sort
) > "$TMP_RULES"

# Gather topic and category counts.
declare -A CATEGORY_COUNTS
declare -A TOPIC_COUNTS
TOTAL_RULES=0

while IFS= read -r file; do
  IFS='/' read -r _ category topic _rest <<< "$file"
  key="$category/$topic"
  CATEGORY_COUNTS["$category"]=$(( ${CATEGORY_COUNTS["$category"]:-0} + 1 ))
  TOPIC_COUNTS["$key"]=$(( ${TOPIC_COUNTS["$key"]:-0} + 1 ))
  TOTAL_RULES=$((TOTAL_RULES + 1))
done < "$TMP_RULES"

# Top-level governance files relevant to rule usage.
readarray -t PROMPT_FILES < <(find "$REPO_ROOT" -maxdepth 1 -type f -name 'PROMPT_*.md' | sed "s|$REPO_ROOT/||" | sort)
GOVERNANCE_FILES=(
  "RULES.md"
  "README.md"
  "ROO_WORKSPACE_POLICY.md"
)

# Build rules-summary.md
{
  echo "# Enterprise Rules Summary"
  echo
  echo "Generated by: \`build-rules-catalog.sh\`"
  echo
  echo "## Totals"
  echo "- Rule artifacts under \`generative/\`: $TOTAL_RULES"
  echo "- Top-level governance docs: ${#GOVERNANCE_FILES[@]}"
  echo "- Top-level operational prompts: ${#PROMPT_FILES[@]}"
  echo
  echo "## Top-Level Governance Docs"
  for file in "${GOVERNANCE_FILES[@]}"; do
    echo "- \`$file\`"
  done
  echo
  echo "## Top-Level Operational Prompts"
  for file in "${PROMPT_FILES[@]}"; do
    echo "- \`$file\`"
  done
  echo
  echo "## Rule Counts by Category"
  for category in "${!CATEGORY_COUNTS[@]}"; do
    printf '%05d %s\n' "${CATEGORY_COUNTS[$category]}" "$category"
  done | sort -rn | while read -r line; do
    count="${line%% *}"
    category="${line#* }"
    echo "- \`$category\`: $((10#$count))"
  done
  echo
  echo "## Rule Counts by Topic"
  for topic in "${!TOPIC_COUNTS[@]}"; do
    printf '%s,%d\n' "$topic" "${TOPIC_COUNTS[$topic]}"
  done | sort | while IFS=',' read -r topic count; do
    echo "- \`$topic\`: $count"
  done
} > "$REFERENCES_DIR/rules-summary.md"

# Build topic-readmes.md
find "$REPO_ROOT/generative" -mindepth 1 -maxdepth 1 -type d | sed "s|$REPO_ROOT/||" | sort > "$TMP_TOPICS"

{
  echo "# Topic README Index"
  echo
  echo "Generated by: \`build-rules-catalog.sh\`"
  echo
  echo "## Root"
  echo "- \`generative/README.md\`"
  while IFS= read -r category_dir; do
    echo "- \`$category_dir/README.md\`"
  done < "$TMP_TOPICS"
  echo
  echo "## Topic Entry Points"
  find "$REPO_ROOT/generative" -mindepth 2 -maxdepth 2 -type d | sed "s|$REPO_ROOT/||" | sort | while IFS= read -r topic_dir; do
    echo "- \`$topic_dir/README.md\`"
  done
} > "$REFERENCES_DIR/topic-readmes.md"

# Build rules-inventory.md
{
  echo "# Comprehensive Rules Inventory"
  echo
  echo "Generated by: \`build-rules-catalog.sh\`"
  echo
  echo "Total rule artifacts: $TOTAL_RULES"
  echo
  echo "Selection scope: files matching \`*.rules.md\`, \`*.rules.xml\`, and \`**/rules/*.md\` under \`generative/\`."
  echo
  current_topic=""
  while IFS= read -r file; do
    IFS='/' read -r _ category topic _rest <<< "$file"
    topic_key="$category/$topic"
    if [[ "$topic_key" != "$current_topic" ]]; then
      if [[ -n "$current_topic" ]]; then
        echo
      fi
      echo "## $topic_key (${TOPIC_COUNTS[$topic_key]})"
      current_topic="$topic_key"
    fi
    echo "- \`$file\`"
  done < "$TMP_RULES"
} > "$REFERENCES_DIR/rules-inventory.md"

echo "Updated:"
echo "- $REFERENCES_DIR/rules-summary.md"
echo "- $REFERENCES_DIR/topic-readmes.md"
echo "- $REFERENCES_DIR/rules-inventory.md"
